import { type RouteConfig, index, layout, route } from "@react-router/dev/routes";
export default [
    index("routes/index.tsx"),
    route("bang-dieu-khien", "routes/Dashboard.jsx", {
        id: "dashboard",
    }, [
        index("routes/indexDashboard.jsx"),
        route(`chuong-trinh-hoc/bai-giang/:classId`, "routes/dashboard/lessons.jsx"),
        route(`chuong-trinh-hoc/:class/:file_type`, "routes/media.jsx"),
        route(`suu-tap/:file_type`, "routes/collection.jsx"),
        route(`tuy-chinh/:category`, "routes/category.jsx"),
        route(`thong-tin-suu-tam/:categorySlug`, "routes/document.jsx"),
        route(`thong-tin-suu-tam/tao-moi/:categoryId`, "routes/document/documentCreate.jsx"),
        route(`thong-tin-suu-tam/chinh-sua/:documentId`, "routes/document/documentEdit.jsx"),
        route(`thong-tin-suu-tam/xem/:documentId`, "routes/document/documentView.jsx"),
        route(`tim-kiem`, "routes/search.jsx"),
        route(`tim-kiem-tai-lieu`, "routes/searchDoc.jsx"),
        route(`tim-kiem-bai-giang`, "routes/searchLesson.jsx"),
        route(`chuong-trinh-hoc/bai-giang/create/:classId?`, "routes/dashboard/createLesson.jsx"),
        route(`chuong-trinh-hoc/bai-giang/edit/:lessonId`, "routes/dashboard/editLesson.jsx"),
        route("admin", "routes/admin.jsx"),
    ]),
    layout("layouts/authen/Authen.jsx", [
        route("dang-nhap", "routes/Login.jsx"),
        route("dang-ky", "routes/Register.jsx"),
        route("verify-email", "routes/VerifyEmail.jsx"),
    ]),
    route("logout", "routes/actions/logout.jsx"),
    route("upload/:path", "routes/actions/upload.jsx"),
    route("updateFile", "routes/actions/updateFile.jsx"),
    route("deleteFile", "routes/actions/deleteFile.jsx"),
    route("api/category", "routes/actions/category.jsx"),
    route("api/filterFile", "routes/actions/filterFile.jsx"),
    route("api/lesson", "routes/actions/lesson.jsx"),
    route("api/document", "routes/actions/document.jsx"),
    route("api/document/pdf/:documentId", "routes/actions/exportPDF.jsx"),
    route("api/document/word/:documentId", "routes/actions/exportWord.jsx"),
    route("api/document/filter", "routes/actions/documentFilter.jsx"),
    route("api/lesson/filter", "routes/actions/lessonFilter.jsx"),
] satisfies RouteConfig;
